// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRB3BbbibNJVTl_ATSNBPu85sjrXcv-F0',
    appId: '1:623970919477:web:0d7fe0a525a1d96f8f3d7c',
    messagingSenderId: '623970919477',
    projectId: 'contacts-app-9ead8',
    authDomain: 'contacts-app-9ead8.firebaseapp.com',
    storageBucket: 'contacts-app-9ead8.firebasestorage.app',
    measurementId: 'G-6NLP06Z62Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL9pVnuorx9PqZk18rb5o-E84E64PkNXo',
    appId: '1:623970919477:android:c702010322d81afc8f3d7c',
    messagingSenderId: '623970919477',
    projectId: 'contacts-app-9ead8',
    storageBucket: 'contacts-app-9ead8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAglKNMeQFClg0x5NNnkqxImhq-GT1R3cU',
    appId: '1:623970919477:ios:7bd311924cc1727a8f3d7c',
    messagingSenderId: '623970919477',
    projectId: 'contacts-app-9ead8',
    storageBucket: 'contacts-app-9ead8.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

}